import './globals.css'
import { Inter } from 'next/font/google'
import Navbar from './components/Navbar'
import ProfilePhoto from './components/ProfilePhoto'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'My Blog',
  description: 'My Blog. Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en" className="dark">
      <body className="dark:bg-slate-800">
        <Navbar />
        <ProfilePhoto />
        {children}
      </body>
    </html>
  )
}
